accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'account'

urlpatterns = [
    path('profile/', views.Profile.as_view(), name='profile'),
    path('profile/receipt/<int:id>/', views.ProfileReceipt.as_view(), name='pro_receipt'),
    path('address/', views.UserAddress.as_view(), name='address'),
    path('address/change/', views.ChangeAddress.as_view(), name='change'),
    path('address/delete/<int:id>/', views.DeleteAddress.as_view(), name='delete'),
]

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('',views.Home.as_view(), name='home'),
    path('register/',views.Register.as_view(), name='register'),
    path('otp_confirm/',views.OtpConfirm.as_view(), name='otp_confirm'),
    path('login/',views.Login.as_view(), name='login'),
    path('about/',views.About.as_view(), name='about'),
    path('contactus/',views.Contactus.as_view(), name='contactus'),
    path('forgot/',views.Forgot.as_view(), name='forgot'),
    path('logout/',views.UserLogout.as_view(), name='logout'),
]

managers/urls.py
from django.urls import path
from managers import views


app_name = 'manager'

urlpatterns = [
    path('manage/', views.Manage.as_view(), name='manage'),
]

meatshop/urls.py
from django.contrib import admin
from django.urls import path, include
from meatshop import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('product.urls', namespace='product')),
    path('zarinpal/', include('zarinpal.urls', namespace='zarinpal')),
    path('order/', include('order.urls', namespace='order')),
    path('account/', include('accounts.urls', namespace='account')),
    path('manager/', include('managers.urls', namespace='manager')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from order import views


app_name = 'order'

urlpatterns = [
    path('shoping_card/', views.ShopingCard.as_view(), name='shoping_card'),
    path('shoping_card/add/<str:product>/', views.ShopingCardUpdate.as_view(), name='shoping_card_update'),
    path('shoping_card/remove/<str:product>/', views.RemoveItem.as_view(), name='item_remove'),
    path('card/add/<int:product_id>/', views.CardAddProduct.as_view(), name='card_add'),
    path('receipt/', views.UserReceipt.as_view(), name='receipt'),
    path('pay/<int:order_id>/', views.OrderPay.as_view(), name='order_pay'),
    path('verify/', views.OrderPayVerify.as_view(), name='order_verify'),
]

home/models.py
from django.db import models


class ContactUs(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    subject = models.CharField(max_length=250)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'contact us'
        verbose_name_plural = 'contact us'
        ordering = ('created',)

    def __str__(self) -> str:
        return self.subject

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from accounts.models import User, OtpCode
from home.models import ContactUs
from django.utils import timezone
from product.models import Category, Product
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from order.models import OrderItem
from django.db.models import Count
from utils import msg_sender
from django.contrib import messages
import random

class Home(View):
    home_temp = 'index.html'
    def get(self, request):
        temp = self.home_temp
        eco_prod = Product.objects.filter(status=True, inventory__gt=0, economic=True) 
        products = Product.objects.filter(status=True, inventory__gt=0)
        top_items = OrderItem.objects.values('product_id').annotate(total=Count('product_id')).order_by('-total')[:4]
        top_product_ids = [item['product_id'] for item in top_items]
        top_products = Product.objects.filter(name__in=top_product_ids, inventory__gt=0)
        return render(request, temp, {'products': products, 'economic': eco_prod, 'best_sellers': top_products})
    
    def post(self, request):
        pass


class Register(View):
    reg_temp = 'inc/register.html'
    otp_temp = 'inc/otp-input.html'
    success_tem = 'inc/reg-done.html'

    def get(self, request):
        messages.info(request, 'لطفا زبان نوشتن را روی حالت انگلیسی قرار دهید')
        return render(request, self.reg_temp)
    
    def post(self, request):
        phone_number_checker = User.objects.filter(phone_number=request.POST['phone']).exists()
        
        if phone_number_checker:
            return render(request, self.reg_temp, {'alert': 'شماره تلفن تکراری! ، لطفا شماره دیگری را وارد کنید.'})
        if request.POST['password1'] != request.POST['password2']:
            return render(request, self.reg_temp, {'alert': 'رمز هایی که وارد کرده اید با هم برابر نیستند.'})
        
        otp_code = random.randint(10000, 99999)
        user_code_exists = OtpCode.objects.filter(phone_number=request.POST['phone']).exists()
        if user_code_exists:
            user_code_created_time = OtpCode.objects.filter(phone_number=request.POST['phone']).values_list('created', flat=True).first()
            current_time = timezone.now()
            time_difference = current_time - user_code_created_time

            if time_difference.total_seconds() > 120:
                user_code_exists = OtpCode.objects.filter(phone_number=request.POST['phone']).delete()
                OtpCode.objects.create(phone_number=request.POST['phone'],
                                       email=request.POST['email'],
                                       code=otp_code)

            else:
                otp_code = OtpCode.objects.filter(phone_number=request.POST['phone']).values_list('code', flat=True).first()
            
        else:
            OtpCode.objects.create(phone_number=request.POST['phone'],
                                       email='register@sample.com',
                                       code=otp_code)
        
        request.session['user_register_info'] = {
                    'phone_number': request.POST['phone'],
                    'full_name': request.POST['name'],
                    'password': request.POST['password2']
                    }
        message = f'کد تایید ثبت نام شما : {otp_code} \n www.Qasaab.ir'
        msg_sender(request.POST['phone'], message)
        return render(request, self.otp_temp)


class OtpConfirm(View):
    otp_temp = 'inc/otp-input.html'
    success_temp = 'inc/reg-done.html'    
    
    def post(self, request):
        user_phone = request.session['user_register_info']['phone_number']
        user_full_name = request.session['user_register_info']['full_name']
        user_password = request.session['user_register_info']['password']
        otp_code = OtpCode.objects.filter(phone_number=user_phone).values_list('code', flat=True).first()
        
        if int(otp_code)==int(request.POST['code']):
            User.objects.create(
                phone_number=user_phone,
                full_name=user_full_name,
                password=user_password
            )
            OtpCode.objects.filter(phone_number=user_phone).delete()
            del request.session['user_register_info']
            return render(request, self.success_temp)
        return render(request, self.otp_temp, {'alert': 'کد یکبار مصرف وارد شده صحیح نمی باشد'})


class Login(View):
    log_temp = 'inc/login.html'
    home_temp = 'index.html'

    def get(self, request):
        return render(request, self.log_temp)
    
    def post(self, request):
        user = authenticate(request, phone_number=request.POST['phone'], 
                            password=request.POST['password'])
        if user is not None:
            login(request, user)
            return redirect('home:home')
        return render(request, self.log_temp, {'alert': 'شماره تلفن و یا رمز وارد شده معتبر نیست.'})

    

class Forgot(View):
    forgot_temp = 'inc/forgot-pass.html'
    login_temp = 'inc/login.html'

    def get(self, request):
        phone = request.GET['phone']
        user_exists = User.objects.filter(phone_number=phone).exists()
        if not user_exists:
            return render(request, self.login_temp, {'alert': 'کاربری با اطلاعات وارد شده در سایت ثبت نام نکرده است'})
        otp_code = random.randint(100000, 999999)
        OtpCode.objects.create(phone_number=phone, email='forgot@mail.com', code=otp_code)
        request.session['user_forgot_password'] = {
            'user_phone': phone
        }
        message = f'اگر شما کد فراموشی رمز را درخواست نداده اید این پیام را نادیده بگیرید. \n کد تایید شما: {otp_code} \n www.Qasaab.ir'
        msg_sender(phone, message)
        return render(request, self.forgot_temp)

    def post(self, request):
        code = request.POST['code']
        pass1 = request.POST['password1']
        pass2 = request.POST['password2']

        code_sent = OtpCode.objects.filter(phone_number=request.session['user_forgot_password']['user_phone']).values_list('code', flat=True).first()
        user_phone = request.session['user_forgot_password']['user_phone']
        user = User.objects.get(phone_number=user_phone)
        code_exist = OtpCode.objects.filter(phone_number=request.session['user_forgot_password']['user_phone'],
                                             email='forgot@mail.com').exists()
        
        if code_exist and int(code_sent)==int(code):
            if str(pass1)==str(pass2):
                user.set_password(pass2)
                user.save()
                OtpCode.objects.filter(phone_number=request.session['user_forgot_password']['user_phone']).delete()
                del request.session['user_forgot_password']
                return render(request, self.login_temp, {'alert': 'رمز با موفقیت تغییر کرد'})
            else:
                return render(request, self.forgot_temp, {'alert': 'رمز اول با تکرار رمز برابر نیست'})
        else:
            return render(request, self.forgot_temp, {'alert': 'کد وارد شده صحیح نیست و یا منقضی شده است'})



class About(View):
    about_temp = 'about.html'

    def get(self, request):
        return render(request, self.about_temp)
    

class Contactus(View):
    cont_temp = 'contactus.html'

    def get(self, request):
        return render(request, self.cont_temp)
    
    def post(self, request):
        ContactUs.objects.create(
            name = request.POST['name'],
            email = request.POST['email'],
            subject = request.POST['subject'],
            message = request.POST['message']
        )
        messages.success(request, 'با تشکر ،پیام شما با موفقیت برای ما ارسال شد.')
        return redirect('home:contactus')


class UserLogout(LoginRequiredMixin, View):
    temp = 'index.html'

    def get(self, request):
        logout(request)
        return redirect('home:home')

home/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% include 'header.html' %}
    <body>
       {% include 'navigation.html' %}
        <!-- About Section Start -->
        <section class="py-3 py-md-5 py-xl-8 " dir="rtl">
            <div class="container">
                <div class="row gy-3 gy-md-4 gy-lg-0">
                    <div class="col-12 col-lg-12">
                        <div class="card bg-light p-3 m-0 shadow-sm" style="border: 1px dashed #000;">
                            <div class="row gy-3 gy-md-0 align-items-md-center">
                                <h5 class="fs-5 mb-2 text-secondary text-uppercase">درباره ما</h5>
                                <h6 class="display-8 mb-4 text-center">
                                    دامیران، از مجموعه‌های پیشرو در زمینه بسته‌بندی و پخش گوشت با بیش از یک دهه تجربه، با افتخار به عنوان یکی از برترین تامین‌کنندگان گوشت در بازار زیاران و حومه شناخته شده است. ما با بهره‌گیری از فناوری‌ و استفاده از استانداردهای بهداشتی و کنترل کیفیت، محصولات بی‌نظیری را به مشتریان عرضه می‌کنیم. ما به ارائه گوشت با کیفیت بالا، تازه و مرغوب با توجه به نیازهای مشتریان و ایجاد رضایت بی‌پایان آنها متعهد هستیم. هدف ما از راه‌اندازی دامیران، ایجاد اعتماد مشتریان و ارائه بهترین خدمات و محصولات گوشتی برای تامین سلامتی و رضایت شماست.                    
                                </h6>
                            </div>
                        </div>
                    </div>                    
                </div>
            </div>
            <br>            
            <div class="container">
            <div class="row gy-3 gy-md-4 gy-lg-0">
                <div class="col-12 col-lg-12">
                <div class="card bg-light p-3 m-0 shadow-sm" style="border: 1px dashed #000;">
                    <div class="row gy-3 gy-md-0 align-items-md-center">
                    <div class="col-md-5">
                        <img src="{% static 'home/assets/img/DSC_7697.jpg' %}" class="img-fluid rounded-start" alt="..." style="height: 350px;">
                    </div>
                    <div class="col-md-7">
                        <div class="card-body p-0">
                        <h4 class="card-title h4 mb-1">چرا دامیران را انتخاب میکنید؟</h4>
                        <p class="card-text h6">
                            1. کیفیت بالا: ما در دامیران به کیفیت بالای محصولات خود افتخار می‌کنیم. از مرحله‌ی انتخاب مواد اولیه تا بسته‌بندی و ارسال، کیفیت همواره در اولویت ما قرار دارد.
                            2. تازگی محصولات: ما اطمینان می‌یابیم که محصولات ما همواره تازه و با کیفیت بالا به شما عرضه می‌شوند، زیرا ما به انتخاب دقیق و استاندارد مواد اولیه می‌پردازیم.
                            3. تنوع محصولات: از گوشت قرمز تا مرغ و ماهی، در دامیران می‌توانید انواع مختلفی از محصولات گوشتی را پیدا کنید و انتخاب خود را بر اساس نیازهای خود انجام دهید.
                            4. خدمات مشتریان برتر: تیم خدمات مشتریان ما همواره آماده‌ی پاسخگویی به سوالات شما و ارائه‌ی راهکارهای مناسب برای نیازهای شماست.
                            5. تحویل سریع: ما به ارائه خدمات تحویل سریع و مطمئن به مشتریان خود تاکید داریم تا شما بتوانید به سرعت از محصولات ما بهره‌مند شوید.
                            6. قیمت رقابتی: ما در دامیران به ارائه قیمت‌های رقابتی و منصفانه برای محصولاتمان اهمیت می‌دهیم تا به شما امکان خرید با اطمینان و رضایت را بدهیم.
                            7. تضمین بهداشت: ما از استانداردهای بهداشتی بالا در تمامی مراحل تولید و توزیع محصولاتمان پیروی می‌کنیم تا بهترین امکانات بهداشتی را برای مشتریانمان فراهم کنیم.
                            8. محیط زیست و پایداری: ما در دامیران به حفظ محیط زیست و استفاده پایدار از منابع محیطی توجه ویژه‌ای داریم و در تمامی فعالیت‌هایمان از رویکردهای پایدار استفاده می‌کنیم.
                        </p>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
                <div>
                    <br>
                    <a href="{% url 'home:home' %}" class="btn btn-outline-success flex-shrink-0 me-3">بازگشت به صفحه اصلی</a>
                </div>
            </div>
            </div>
        </section>
        <!-- About Section End -->
        
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>

        {% include 'footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>

    </body>
</html>

home/templates/contactus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% include 'header.html' %}
    <body>
       {% include 'navigation.html' %}
       <br>
       <nav aria-label="breadcrumb" >
           <ol class="breadcrumb" ><a class="bi bi-geo-fill"></a>
            <li class="breadcrumb-item"><a href="#">خانه</a></li>
            <li class="breadcrumb-item active" aria-current="page"> ارتباط با ما</li>
        </ol>
    </nav>

        <!--Section: Contact v.2-->
        <div class="container my-5" dir="rtl">
            <div class="row " style="margin-left: 0px; margin-right: 0px;">
                <div class="card h-100" >
                    <div class="card-body shadow-sm text-center">
                        <section class="mb-4">

                            <!--Section heading-->
                            <div class="user-avatar">
                                <h2 class="h1-responsive font-weight-bold text-center my-4">ارتباط با ما<img src="{% static 'home/assets/favicon.png' %}" alt="Maxwell Admin" style="width: 70px;" class="rounded-pill"></h2>
                                
                            </div>
                            <!--Section description-->
                            <p class="w-responsive mx-auto mb-5 text-white btn" style="background-color: crimson;">آیا با مشکلی مواجه شده اید؟ جای نگرانی نیست ، کافیه به ما پیام بدید یا با ما تماس بگیرید.</p>

                            <div class="row">

                                <!--Grid column-->
                                <div class="col-md-9 mb-md-0 mb-5 rounded" style="border: 1px dashed #000;">
                                    <br>
                                    <form action="" method="post">
                                    {% csrf_token %}
                                        <!--Grid row-->
                                        <div class="row">

                                            <!--Grid column-->
                                            <div class="col-md-6">
                                                <div class="md-form mb-0">
                                                    <input type="text" id="name" name="name" class="form-control" required>
                                                    <label for="name" class=""> اسم شما</label>
                                                </div>
                                            </div>
                                            <!--Grid column-->

                                            <!--Grid column-->
                                            <div class="col-md-6">
                                                <div class="md-form mb-0">
                                                    <input type="text" id="email" name="email" class="form-control" required>
                                                    <label for="email" class="">ایمیل شما </label>
                                                </div>
                                            </div>
                                            <!--Grid column-->

                                        </div>
                                        <!--Grid row-->

                                        <!--Grid row-->
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="md-form mb-0">
                                                    <input type="text" id="subject" name="subject" class="form-control" required>
                                                    <label for="subject" class="">موضوع</label>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Grid row-->

                                        <!--Grid row-->
                                        <div class="row">

                                            <!--Grid column-->
                                            <div class="col-md-12">
                                                <div class="md-form">
                                                    <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea" required></textarea>
                                                    <label for="message">پیام شما </label>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Grid row-->
                                        <br>
                                        <button class="btn btn-primary" type="submit">ارسال پیام</button>    
                                    </form>
                                    <br>
                                </div>
                                <!--Grid column-->

                                <!--Grid column-->
                                <div class="col-md-3 text-center">
                                    <ul class="list-unstyled mb-0">
                                        <li><i class="fas fa-map-marker-alt fa-2x"></i>
                                            <p>زیاران - خیابان شهید سلیمانی</p>
                                        </li>

                                        <li><i class="fas fa-phone mt-4 fa-2x"></i>
                                            <p>09126818407</p>
                                        </li>

                                        <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                                            <p>info@qasaab.ir</p>
                                        </li>
                                    </ul>
                                </div>
                                <!--Grid column-->

                            </div>
                            
                        </section>
                    </div>
                </div>
                <div>
                    <br>
                    <a href="{% url 'home:home' %}" class="btn btn-outline-success flex-shrink-0 me-3">بازگشت به صفحه اصلی</a>
                </div>
            </div>
        </div>
            <!--Section: Contact v.2-->
        
        {% if alert %}
        <div class="error-message">
          <script>
              alert("{{ alert }}");
          </script>
        </div>
        {% endif %}

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success" role="alert">
                    <script>
                        alert("{{ message }}");
                    </script>
                </div>
            {% endfor %}
        {% endif %}


        {% include 'footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>

    </body>
</html>

home/templates/footer.html
{% load static %}
<!-- Footer Start -->
<footer class="text-center text-white" style="background-color:slategrey; color: black;">
    <!-- Grid container -->
    <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
        <!-- Facebook -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="bi bi-facebook"></i
        ></a>

        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="bi bi-twitter"></i
        ></a>

        <!-- Google -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="bi bi-google"></i
        ></a>

        <!-- Instagram -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="bi bi-instagram"></i
        ></a>

        <!-- Linkedin -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="bi bi-linkedin"></i
        ></a>

        <!-- Github -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="bi bi-github"></i
        ></a>
    </section>
    <!-- Section: Social media -->

    <!-- Section: Text -->
    <section class="mb-4">
        <p>
            دامیران، یک تیم پر انرژی و متعهد است که به فراهم آوردن بهترین تجربه خرید گوشت برای مشتریان خود متعهد است.
            ما به کیفیت، تازگی و ارزش افزوده از طریق انتخاب دقیق گوشت‌های باکیفیت و ارائه خدمات به موقع و حرفه‌ای تمرکز داریم.
            با رویکردی مشتری‌محور، تلاش می‌کنیم تا اطمینان و رضایت کامل مشتریان خود را به دست آوریم. به ما بپیوندید و از تجربه خرید لذت ببرید
        </p>
    </section>
    <!-- Section: Text -->

    <!-- Section: Links -->
    <section class="">
        <!--enamad row-->
        <div class="row justify-content-center">
            <div class="col-md-1">            
                <a referrerpolicy='origin' target='_blank' href='https://trustseal.enamad.ir/?id=466369&Code=0KkAI6Ip69NytYBBLq4YBaXVJyhND7Ih'>
                    <img referrerpolicy='origin' src='https://trustseal.enamad.ir/logo.aspx?id=466369&Code=0KkAI6Ip69NytYBBLq4YBaXVJyhND7Ih' alt='' style='cursor:pointer' Code='0KkAI6Ip69NytYBBLq4YBaXVJyhND7Ih'>
                </a>
            </div>
            <div class="col-md-1">            
                <script src="https://www.zarinpal.com/webservice/TrustCode" type="text/javascript"></script>
            </div>
        </div>
        <!--Grid row-->
    </section>
    <!-- Section: Links -->
    
    <!-- Grid container -->    
</footer>
<div class="text-center text-white" style="background-color:lightsteelblue; margin-left: 0%;">
    طراحی و پشتیبانی توسط :
   <a class="text-white-60 " href="https://github.com/Abbas-moradi" target="_blank" style="text-decoration: none;"> تیم مدیریت دامیران</a>
   </div>
<!-- Footer End -->

home/templates/header.html
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>فروشگاه گوشت دامیران</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.png' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    <!-- CSS Files -->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.2/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.3/components/abouts/about-4/assets/css/about-4.css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function(){
            $(".close-icon").click(function(){
                $(".adverb").hide();
            });
        });
    </script>

</head>

home/templates/navigation.html
{% load static %}
<!-- Navigation Start -->
<nav id="navbar" class="navbar navbar-expand-lg navbar-light bg-light ">
    <div class="container px-4 px-lg-5 ">
        <form class="d-flex">
            <a class="btn btn-outline-dark" href="{% url 'home:about' %}">
                <i class="me-1"></i>
                گوشت دامیران <img src="{% static 'home/assets/favicon.png' %}" alt="عکس" style="height: 30px;">
            </a>
        </form>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                {% if request.user.is_authenticated %}
                    {% if request.user.is_admin %}
                        <li class="nav-item"><a class="nav-link active bi-gear rounded-pill" style="background-color: crimson;" href="{% url 'manager:manage' %}">پنل مدیریت</a></li>
                    {% endif %}
                {% endif %}

                {% if request.user.is_authenticated %}
                <li class="nav-item"><a class="nav-link active bi-person" aria-current="page" href="{% url 'account:profile' %}">حساب کاربری</a></li>
                {% endif %}
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">خانه</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'home:about' %}">درباره ما</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">صفحه ها</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">همه محصولات</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        {% if request.user.is_authenticated %}
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'home:register' %}">ثبت نام </a></li>
                        {% endif %}
                        <li><a class="dropdown-item" href="#best-sellers">محصولات اقتصادی  </a></li>
                        <li><a class="dropdown-item" href="{% url 'home:contactus' %}">ارتباط با ما</a></li>
                        <li><a class="dropdown-item" href="#!"> مجوزها </a></li>
                    </ul>
                </li>
            </ul>
        </div>
            <a class="btn btn-outline-dark" href="{% url 'order:shoping_card' %}">
                سبد خرید
                <i class="bi bi-cart-fill me-1"></i>
                {% if item_number|length > 0 %}
                    <span class="badge bg-danger text-white ms-1 rounded-pill">{{ item_number|length }}</span>
                {% endif %}
            </a>                  
    </div>      
</nav>
<div id="mini-navbar" class="mini-nav shadow-sm">
    <div class="container " dir="rtl">
        <div class="d-flex justify-content-between">
            {% if request.user.is_authenticated %}
            <a class="nav-link" href="{% url 'home:logout' %}">خروج از حساب</a>
            <div style="text-align: center; border: 1px dashed #767676;">
                <p class="" >کاربر گرامی، {{ request.user.full_name }}،  به فروشگاه گوشت دامیران خوش آمدید</p>
            </div>
            {% else %}
            <div class="d-flex justify-content-end align-items-center">
                <a class="nav-link bi bi-person" href="{% url 'home:register' %}" style="margin-right: 5px;">ثبت نام</a>
                <a class="nav-link" href="{% url 'home:login' %}" style="margin-left: 5px;">/ ورود</a>
            </div>
            {% endif %}
            <div style="align-items: end;">
                <p>امروز {{ jalali }}</p>
            </div>
        </div>
    </div>
</div>
<!-- Navigation End -->