accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'account'

urlpatterns = [
    path('profile/', views.Profile.as_view(), name='profile'),
    path('profile/receipt/<int:id>/', views.ProfileReceipt.as_view(), name='pro_receipt'),
    path('address/', views.UserAddress.as_view(), name='address'),
    path('address/change/', views.ChangeAddress.as_view(), name='change'),
    path('address/delete/<int:id>/', views.DeleteAddress.as_view(), name='delete'),
]

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('',views.Home.as_view(), name='home'),
    path('register/',views.Register.as_view(), name='register'),
    path('otp_confirm/',views.OtpConfirm.as_view(), name='otp_confirm'),
    path('login/',views.Login.as_view(), name='login'),
    path('about/',views.About.as_view(), name='about'),
    path('contactus/',views.Contactus.as_view(), name='contactus'),
    path('forgot/',views.Forgot.as_view(), name='forgot'),
    path('logout/',views.UserLogout.as_view(), name='logout'),
]

meatshop/urls.py
from django.contrib import admin
from django.urls import path, include
from meatshop import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('product.urls', namespace='product')),
    path('zarinpal/', include('zarinpal.urls', namespace='zarinpal')),
    path('order/', include('order.urls', namespace='order')),
    path('account/', include('accounts.urls', namespace='account')),
    path('manager/', include('managers.urls', namespace='manager')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from order import views


app_name = 'order'

urlpatterns = [
    path('shoping_card/', views.ShopingCard.as_view(), name='shoping_card'),
    path('shoping_card/add/<str:product>/', views.ShopingCardUpdate.as_view(), name='shoping_card_update'),
    path('shoping_card/remove/<str:product>/', views.RemoveItem.as_view(), name='item_remove'),
    path('card/add/<int:product_id>/', views.CardAddProduct.as_view(), name='card_add'),
    path('receipt/', views.UserReceipt.as_view(), name='receipt'),
    path('pay/<int:order_id>/', views.OrderPay.as_view(), name='order_pay'),
    path('verify/', views.OrderPayVerify.as_view(), name='order_verify'),
]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'

urlpatterns = [
    path('<slug:slug>/', views.ProductDetail.as_view(), name='product_detail'),
]

home/models.py
from django.db import models


class ContactUs(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    subject = models.CharField(max_length=250)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'contact us'
        verbose_name_plural = 'contact us'
        ordering = ('created',)

    def __str__(self) -> str:
        return self.subject

product/models.py
from django.db import models
from django.urls import reverse
from accounts.models import User 


class Product(models.Model):
    name = models.CharField(max_length = 200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()
    price = models.PositiveIntegerField()
    inventory = models.PositiveIntegerField()
    number = models.PositiveSmallIntegerField(default=1)
    pic = models.ImageField(upload_to='product/')
    discount = models.PositiveSmallIntegerField()
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='products')
    economic = models.BooleanField(default=False)
    UNIT_CHOICES = (
        ('کیلوگرم', 'kg'),
        ('بسته', 'pk'),
        ('یک دست', 'st')
    )
    unit = models.CharField(max_length=10, choices=UNIT_CHOICES)
    status = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'
        ordering = ('created',)
    
    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('product:product_detail', args=[self.slug,])
    
    
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)
    pic = models.ImageField(upload_to='category/')
    created = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ('created',)

    def __str__(self) -> str:
        return f'{self.name}'
    

class ProductComment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    shamsi = models.CharField(max_length=150)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'
        ordering = ('created',)

    def __str__(self) -> str:
        return f'{self.user} - {self.comment}'

home/views.py
from django.shortcuts import render, redirect
from django.views import View
from accounts.models import User, OtpCode
from home.models import ContactUs
from django.utils import timezone
from product.models import Category, Product
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from order.models import OrderItem
from django.db.models import Count
from utils import msg_sender
from django.contrib import messages
import random

class Home(View):
    home_temp = 'index.html'
    def get(self, request):
        temp = self.home_temp
        eco_prod = Product.objects.filter(status=True, inventory__gt=0, economic=True) 
        products = Product.objects.filter(status=True, inventory__gt=0)
        top_items = OrderItem.objects.values('product_id').annotate(total=Count('product_id')).order_by('-total')[:4]
        top_product_ids = [item['product_id'] for item in top_items]
        top_products = Product.objects.filter(name__in=top_product_ids, inventory__gt=0)
        return render(request, temp, {'products': products, 'economic': eco_prod, 'best_sellers': top_products})
    
    def post(self, request):
        pass


class Register(View):
    reg_temp = 'inc/register.html'
    otp_temp = 'inc/otp-input.html'
    success_tem = 'inc/reg-done.html'

    def get(self, request):
        messages.info(request, 'لطفا زبان نوشتن را روی حالت انگلیسی قرار دهید')
        return render(request, self.reg_temp)
    
    def post(self, request):
        phone_number_checker = User.objects.filter(phone_number=request.POST['phone']).exists()
        
        if phone_number_checker:
            return render(request, self.reg_temp, {'alert': 'شماره تلفن تکراری! ، لطفا شماره دیگری را وارد کنید.'})
        if request.POST['password1'] != request.POST['password2']:
            return render(request, self.reg_temp, {'alert': 'رمز هایی که وارد کرده اید با هم برابر نیستند.'})
        
        otp_code = random.randint(10000, 99999)
        user_code_exists = OtpCode.objects.filter(phone_number=request.POST['phone']).exists()
        if user_code_exists:
            user_code_created_time = OtpCode.objects.filter(phone_number=request.POST['phone']).values_list('created', flat=True).first()
            current_time = timezone.now()
            time_difference = current_time - user_code_created_time

            if time_difference.total_seconds() > 120:
                user_code_exists = OtpCode.objects.filter(phone_number=request.POST['phone']).delete()
                OtpCode.objects.create(phone_number=request.POST['phone'],
                                       email=request.POST['email'],
                                       code=otp_code)

            else:
                otp_code = OtpCode.objects.filter(phone_number=request.POST['phone']).values_list('code', flat=True).first()
            
        else:
            OtpCode.objects.create(phone_number=request.POST['phone'],
                                       email='register@sample.com',
                                       code=otp_code)
        
        request.session['user_register_info'] = {
                    'phone_number': request.POST['phone'],
                    'full_name': request.POST['name'],
                    'password': request.POST['password2']
                    }
        message = f'کد تایید ثبت نام شما : {otp_code} \n www.Qasaab.ir'
        msg_sender(request.POST['phone'], message)
        return render(request, self.otp_temp)


class OtpConfirm(View):
    otp_temp = 'inc/otp-input.html'
    success_temp = 'inc/reg-done.html'    
    
    def post(self, request):
        user_phone = request.session['user_register_info']['phone_number']
        user_full_name = request.session['user_register_info']['full_name']
        user_password = request.session['user_register_info']['password']
        otp_code = OtpCode.objects.filter(phone_number=user_phone).values_list('code', flat=True).first()
        
        if int(otp_code)==int(request.POST['code']):
            User.objects.create(
                phone_number=user_phone,
                full_name=user_full_name,
                password=user_password
            )
            OtpCode.objects.filter(phone_number=user_phone).delete()
            del request.session['user_register_info']
            return render(request, self.success_temp)
        return render(request, self.otp_temp, {'alert': 'کد یکبار مصرف وارد شده صحیح نمی باشد'})


class Login(View):
    log_temp = 'inc/login.html'
    home_temp = 'index.html'

    def get(self, request):
        return render(request, self.log_temp)
    
    def post(self, request):
        user = authenticate(request, phone_number=request.POST['phone'], 
                            password=request.POST['password'])
        if user is not None:
            login(request, user)
            return redirect('home:home')
        return render(request, self.log_temp, {'alert': 'شماره تلفن و یا رمز وارد شده معتبر نیست.'})

    

class Forgot(View):
    forgot_temp = 'inc/forgot-pass.html'
    login_temp = 'inc/login.html'

    def get(self, request):
        phone = request.GET['phone']
        user_exists = User.objects.filter(phone_number=phone).exists()
        if not user_exists:
            return render(request, self.login_temp, {'alert': 'کاربری با اطلاعات وارد شده در سایت ثبت نام نکرده است'})
        otp_code = random.randint(100000, 999999)
        OtpCode.objects.create(phone_number=phone, email='forgot@mail.com', code=otp_code)
        request.session['user_forgot_password'] = {
            'user_phone': phone
        }
        message = f'اگر شما کد فراموشی رمز را درخواست نداده اید این پیام را نادیده بگیرید. \n کد تایید شما: {otp_code} \n www.Qasaab.ir'
        msg_sender(phone, message)
        return render(request, self.forgot_temp)

    def post(self, request):
        code = request.POST['code']
        pass1 = request.POST['password1']
        pass2 = request.POST['password2']

        code_sent = OtpCode.objects.filter(phone_number=request.session['user_forgot_password']['user_phone']).values_list('code', flat=True).first()
        user_phone = request.session['user_forgot_password']['user_phone']
        user = User.objects.get(phone_number=user_phone)
        code_exist = OtpCode.objects.filter(phone_number=request.session['user_forgot_password']['user_phone'],
                                             email='forgot@mail.com').exists()
        
        if code_exist and int(code_sent)==int(code):
            if str(pass1)==str(pass2):
                user.set_password(pass2)
                user.save()
                OtpCode.objects.filter(phone_number=request.session['user_forgot_password']['user_phone']).delete()
                del request.session['user_forgot_password']
                return render(request, self.login_temp, {'alert': 'رمز با موفقیت تغییر کرد'})
            else:
                return render(request, self.forgot_temp, {'alert': 'رمز اول با تکرار رمز برابر نیست'})
        else:
            return render(request, self.forgot_temp, {'alert': 'کد وارد شده صحیح نیست و یا منقضی شده است'})



class About(View):
    about_temp = 'about.html'

    def get(self, request):
        return render(request, self.about_temp)
    

class Contactus(View):
    cont_temp = 'contactus.html'

    def get(self, request):
        return render(request, self.cont_temp)
    
    def post(self, request):
        ContactUs.objects.create(
            name = request.POST['name'],
            email = request.POST['email'],
            subject = request.POST['subject'],
            message = request.POST['message']
        )
        messages.success(request, 'با تشکر ،پیام شما با موفقیت برای ما ارسال شد.')
        return redirect('home:contactus')


class UserLogout(LoginRequiredMixin, View):
    temp = 'index.html'

    def get(self, request):
        logout(request)
        return redirect('home:home')

product/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from django.views import  View


class ProductDetail(View):
    detail_temp = 'inc/detail.html'

    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        return render(request, self.detail_temp, {'product': product})

home/templates/inc/comment.html
{% load static %}
<!-- Comment Section Start -->
<div class="container" dir="rtl">
    <div class="row justify-content-center">
        <div class="card shadow rounded" style="border: 1px dashed #767676;">
            <div class="be-comment-block">
                <h1 class="text-center">نظرات (3)</h1><br><br>
                <div class="be-comment">
                    <div class="be-comment-content">
                        
                            <span class="be-comment-name">Ravi Sah</span>
                            <span class="be-comment-time">
                                <i class="fa fa-clock-o"></i>
                                May 27, 2015 at 3:14am
                            </span>

                        <p class="be-comment-text">
                            Pellentesque gravida tristique ultrices. 
                            Sed blandit varius mauris, vel volutpat urna hendrerit id. 
                            Curabitur rutrum dolor gravida turpis tristique efficitur.
                        </p>
                    </div>
                </div>
                <div class="be-comment">
                    <div class="be-comment-content">
                        <span class="be-comment-name">Ravi Sah</span>
                        <span class="be-comment-time">
                            <i class="fa fa-clock-o"></i>
                            May 27, 2015 at 3:14am
                        </span>
                        <p class="be-comment-text">
                            Nunc ornare sed dolor sed mattis. In scelerisque dui a arcu mattis, at maximus eros commodo. Cras magna nunc, cursus lobortis luctus at, sollicitudin vel neque. Duis eleifend lorem non ant. Proin ut ornare lectus, vel eleifend est. Fusce hendrerit dui in turpis tristique blandit.
                        </p>
                    </div>
                </div>
                <div class="be-comment">
                    <div class="be-comment-content">
                        <span class="be-comment-name">Ravi Sah</span>
                        <span class="be-comment-time">
                            <i class="fa fa-clock-o"></i>
                            May 27, 2015 at 3:14am
                        </span>
                        <p class="be-comment-text">
                            Cras magna nunc, cursus lobortis luctus at, sollicitudin vel neque. Duis eleifend lorem non ant
                        </p>
                    </div>
                </div>
                <form class="form-block">
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">ثبت نظرات</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="لطفا نظر خود را در این قسمت بنویسید"></textarea>
                    </div>

                    {% if request.user.is_authenticated %}
                    <button type="submit" class="btn btn-outline-secondary">ثبت نظر</button>
                    {% else %}
                    <p>برای ثبت نظر <a href="{% url 'home:login' %}">وارد</a> شوید ، اگر ثبت نام نکرده اید از <a href="{% url 'home:register' %}"> اینجا </a>ثبت نام کنید</p>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>

home/templates/inc/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% include 'header.html' %}
    <body>
       {% include 'navigation.html' %}
        <!-- User Login Start -->
        <section class="vh-80" style="background-color: #eee;">
            <br>
            <div class="container" dir="rtl">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <div class="card shadow-sm rounded-3">
                            <div class="card-body p-md-5">
                                <p class="text-center text-success h4">صفحه ورود  <img src="{% static 'home/assets/favicon.png' %}" alt="عکس" style="height: 75px;"></p>
                                <form method="post" action="{% url 'home:login' %}">
                                    {% csrf_token %}
                                    <div class="mb-3" dir="rtl">
                                        <label for="phone" class="form-label">تلفن</label>
                                        <div class="input-group" dir="rtl">
                                            <span class="input-group-text"><i class="bi bi-telephone"></i></span>
                                            <input name="phone" type="tel" class="form-control" id="phone" placeholder="لطفاً تلفن خود را وارد کنید" dir="rtl">
                                        </div>
                                    </div>
                                    <div class="mb-3" dir="rtl">
                                        <label for="password" class="form-label">رمز عبور</label>
                                        <div class="input-group">
                                            <span class="input-group-text"><i class="bi bi-lock"></i></span>
                                            <input name="password" type="password" class="form-control" id="password" placeholder="لطفاً رمز عبور خود را وارد کنید">
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary">ورود</button>
                                    <a type="button" class="btn btn-primary mb-0" href="{% url 'home:register' %}">ثبت نام</a>
                                    <hr class="my-4">
                                </form>
                                <form action="{% url 'home:forgot' %}" method="get">
                                    {% csrf_token %}
                                    <div class="mb-3" dir="rtl">
                                        <label for="phone" class="form-label">شماره تلفن</label>
                                        <div class="input-group">
                                            <span class="input-group-text"><i class="bi bi-phone"></i></span>
                                            <input name="phone" type="phone" class="form-control" id="phone" placeholder="درصورت فراموشی رمز ورود، شماره تلفن خود را وارد کنید" required/>
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-warning">فراموشی رمز</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- User Login End -->
        
        {% if alert %}
        <div class="error-message">
          <script>
              alert("{{ alert }}");
          </script>
        </div>
        {% endif %}

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>

        {% include 'footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>

    </body>
</html>

home/templates/inc/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% include 'header.html' %}
    <body>
       {% include 'navigation.html' %}
       <br>
        <nav aria-label="breadcrumb" >
            <ol class="breadcrumb" ><a class="bi bi-geo-fill"></a>
                <li class="breadcrumb-item"><a href="{% url 'home:home' %}">خانه</a></li>
                <li class="breadcrumb-item active" aria-current="page"> حساب کاربری</li>
            </ol>
        </nav><br>
        
        <!-- User Profile Start -->
        <div dir="rtl">
            <a type="button" class="btn btn-warning" href="{% url 'account:address' %}">مدیریت آدرس ها</a>
            <a type="button" class="btn btn-warning" onclick="showProfileForm()">اطلاعات حساب</a>
        </div><br>
        <div class="container" dir="rtl" >
            <div class="row gutters">
                <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
                    <div class="card h-100 hidden" id="profile-detail">
                        <div class="card-body shadow-sm">
                            <div class="account-settings">
                                <div class="user-profile">
                                    <div class="user-avatar">
                                        <img src="{% static 'home/assets/favicon.png' %}" alt="Maxwell Admin">
                                    </div>
                                    <h5 class="user-name">قصاب دات آی آر</h5>
                                    <h6 class="user-email">www.qasaab.ir</h6>
                                </div>
                                <div class="about">
                                    <p>فروشگاه گوشت دامیران</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
                    <div class="card h-100 hidden" id="profile-form">
                        <div class="card-body shadow-sm rounded" style="border: 1px dashed #767676;">
                            <form action="{% url 'account:profile' %}" method="post">
                                {% csrf_token %}
                                <div class="row gutters">
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                        <div class="form-group">
                                            <label for="fullName">نام کامل</label>
                                            <input name="full_name" class="form-control" id="fullName" placeholder="نام کامل" value="{{ user.full_name }}">
                                        </div>
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                        <div class="form-group">
                                            <label for="eMail">ایمیل</label>
                                            <input name="email" class="form-control" id="eMail" placeholder="آدرس ایمیل" value="{{ user.email }}">
                                        </div>
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                        <div class="form-group">
                                            <label for="phone">تلفن</label>
                                            <input name="phone_number" class="form-control" id="phone" placeholder="شماره تلفن" value="{{ user.phone_number }}" readonly>
                                        </div>
                                    </div>
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                        <div class="form-group">
                                            <label for="website"> رمز عبور(حداقل 8 کاراکتر) </label>
                                            <input name="password" type="password" class="form-control" id="website" placeholder="رمز عبور(حداقل 8 کاراکتر)">
                                        </div>
                                    </div>
                                </div>
                                <div class="row gutters">
                                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                        <div class="text-right">
                                            <br>
                                            <button type="submit" id="submit" name="submit" class="btn btn-primary">بروز رسانی</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div><br>
            <div class="row gutters" style="margin-left: 0px; margin-right: 0px;">
                <div class="card h-100 text-center" >
                    <div class="card-body shadow-sm" style="max-height: 350px; overflow-y: auto;">
                    <h5 class="text-center">سوابق خرید شما</h5>
                    <table class="table table-striped ">
                        <thead style="background-color:#84B0CA ;" class="text-white">
                        <tr>
                            <th scope="col">سریال</th>
                            <th scope="col">شماره سفارش</th>
                            <th scope="col">تاریخ سفارش</th>
                            <th scope="col">مبلغ سفارش</th>
                            <th scope="col">وضعیت پرداخت</th>
                            <th scope="col">وضعیت ارسال</th>
                        </tr>
                        </thead>
                        <tbody>
                                {% for ord in order %}
                                <tr>
                                    <th scope="row" type="value" name="address_id" class="th">{{ forloop.counter }}</th>
                                    <td>
                                        <form action="{% url 'account:pro_receipt' ord.id %}" method="get">
                                        {% csrf_token %}
                                            <button type="submit" class="btn btn-info" name="id">{{ ord.id }}</button>
                                        </form>
                                    </td>
                                    <td>{{ ord.shamsi }}</td>
                                    <td>{{ ord.finally_price }} تومان</td>
                                    <td>
                                        {% if ord.paid %}
                                        <span class="badge bg-success text-white fw-bold">پرداخت شده</span>
                                        {% else %}
                                        <span class="badge bg-warning text-black fw-bold">پرداخت نشده</span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if ord.deliver %}
                                        <button type="button" class="btn btn-sm btn-success" data-toggle="popover" title="تحویل شده به آدرس:{{ ord.address }}">تحویل شده</button>
                                        {% else %}
                                        <span class="badge bg-warning text-black fw-bold"  style="color: white;">تحویل نشده</span>
                                        {% endif %}
                                    </td>
                                    
                                </tr>
                                {% endfor %}
                                <p class="text-danger">برای دیدن جزئیات روی شماره رسید <button class="btn btn-info">12</button> کلیک کنید. سفارشات درحالت پرداخت نشده را میتوانید با زدن بر روی گزینه <span class="badge bg-warning text-black fw-bold">پرداخت نشده</span>، پرداخت و دریافت کنید.  </p>
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div><br>
        <!-- User Profile End -->

       
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy;  www.Qasaab.ir 2023</p></div>
        </footer>

        {% if alert %}
        <div class="error-message">
          <script>
              alert("{{ alert }}");
          </script>
        </div>
        {% endif %}

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success" role="alert">
                    <script>
                        alert("{{ message }}");
                    </script>
                </div>
            {% endfor %}
        {% endif %}


        {% include 'footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
        <script>
            function showProfileForm() {
                var profileForm = document.getElementById('profile-form');
                profileForm.classList.remove('hidden');
                var profileForm = document.getElementById('profile-detail');
                profileForm.classList.remove('hidden');
            }
        </script>

        <style>
            .hidden {
                display: none;
            }
        </style>
    </body>
</html>